# Generated by Django 5.0.7 on 2024-07-30 09:28

import companies.models
import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(error_messages={'unique': 'Sellise nimega osaühing on juba olemas.'}, max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(3, 'Osaühingu nimi peab koosnema vähemalt kolmest tähest või numbrist.')])),
                ('reg_code', models.CharField(error_messages={'unique': 'Sellise registrikoodiga osaühing on juba olemas.'}, max_length=7, unique=True, validators=[companies.models.only_int, django.core.validators.MinLengthValidator(6, 'Registrikood peab koosnema seitsmest numbrist.'), django.core.validators.MaxLengthValidator(100, 'Osaühingu nimi ei tohi olla pikem kui 100 tähte või numbrit.')])),
                ('date_founded', models.DateField(default=datetime.date(2024, 7, 30), validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 7, 30), 'Kuupäev peab olema väiksem või võrdne käesoleva kuupäevaga.')])),
                ('total_capital', models.IntegerField(validators=[django.core.validators.MinValueValidator(2500, 'Kogukapitali suurus peab olema vähemalt 2500€.')])),
                ('date_created', models.DateTimeField(default=datetime.datetime(2024, 7, 30, 12, 28, 20, 39177), editable=False)),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Shareholder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(default='', max_length=200)),
                ('share', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Osakapitali suurus peab olema vähemalt 1€.')])),
                ('is_founder', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2024, 7, 30, 12, 28, 20, 97855), editable=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
        ),
    ]
